global:
  scrape_interval: 15s

scrape_configs:
  - job_name: shop-api
    static_configs:
      - targets: ['otel-collector:8889']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: shop-api
